import json

# Your JSON string
json_string1 = "[{\"id\":1,\"values\":[{\"id\":0,\"apiId\":13383,\"moduleId\":13383,\"value\":\"true\",\"inputType\":\"ToggleInput\"},{\"id\":0,\"apiId\":13384,\"moduleId\":13384,\"value\":\"2024-08-22\",\"inputType\":\"DateInput\"},{\"id\":0,\"apiId\":13385,\"moduleId\":13385,\"value\":\"Test\",\"inputType\":\"TextInput\"},{\"id\":0,\"apiId\":13386,\"moduleId\":13386,\"value\":\"3\",\"inputType\":\"DropDownInput\"},{\"id\":0,\"apiId\":13387,\"moduleId\":13387,\"value\":\"[\\\"three\\\",\\\"two\\\"]\",\"inputType\":\"MultiSelectInput\"},{\"id\":0,\"apiId\":13388,\"moduleId\":13388,\"value\":\"Textexte\",\"inputType\":\"TextareaInput\"},{\"id\":0,\"apiId\":13389,\"moduleId\":13389,\"value\":\"153\",\"inputType\":\"NumericInput\"},{\"id\":0,\"apiId\":13390,\"moduleId\":13390,\"value\":\"65.68439789809926\",\"inputType\":\"SeparatedFeetAndInchesInput\"}]}]"
json_string2 = "{\"id\": 13381, \"values\": [{\"ActionName\": null, \"CategoryId\": null, \"Id\": 0, \"InputType\": \"ToggleInput\", \"Label\": \"subToggle\", \"TypeId\": null, \"apiId\": 13383, \"attachmentPropertyIds\": [], \"isEditable\": true, \"isVisible\": true, \"locationId\": null, \"ordinal\": 9, \"subMenuId\": null, \"value\": \"\", \"isDefault\": false, \"parentModuleId\": 13381}, {\"ActionName\": null, \"CategoryId\": null, \"Id\": 0, \"InputType\": \"DateInput\", \"Label\": \"subDate\", \"TypeId\": null, \"apiId\": 13384, \"attachmentPropertyIds\": [], \"isEditable\": true, \"isVisible\": true, \"locationId\": null, \"ordinal\": 10, \"subMenuId\": null, \"value\": \"\", \"isDefault\": false, \"parentModuleId\": 13381}, {\"ActionName\": null, \"CategoryId\": null, \"Id\": 0, \"InputType\": \"TextInput\", \"Label\": \"subText\", \"TypeId\": null, \"apiId\": 13385, \"attachmentPropertyIds\": [], \"isEditable\": true, \"isVisible\": true, \"locationId\": null, \"ordinal\": 11, \"subMenuId\": null, \"value\": \"\", \"isDefault\": false, \"parentModuleId\": 13381}, {\"ActionName\": null, \"CategoryId\": null, \"Id\": 0, \"InputType\": \"DropDownInput\", \"Label\": \"subDropDown\", \"TypeId\": null, \"apiId\": 13386, \"attachmentPropertyIds\": [], \"isEditable\": true, \"isVisible\": true, \"locationId\": null, \"ordinal\": 12, \"subMenuId\": null, \"value\": \"\", \"isDefault\": false, \"parentModuleId\": 13381}, {\"ActionName\": null, \"CategoryId\": null, \"Id\": 0, \"InputType\": \"MultiSelectInput\", \"Label\": \"subMultiSelect\", \"TypeId\": null, \"apiId\": 13387, \"attachmentPropertyIds\": [], \"isEditable\": true, \"isVisible\": true, \"locationId\": null, \"ordinal\": 13, \"subMenuId\": null, \"value\": \"\", \"isDefault\": false, \"parentModuleId\": 13381}, {\"ActionName\": null, \"CategoryId\": null, \"Id\": 0, \"InputType\": \"TextareaInput\", \"Label\": \"subTextarea\", \"TypeId\": null, \"apiId\": 13388, \"attachmentPropertyIds\": [], \"isEditable\": true, \"isVisible\": true, \"locationId\": null, \"ordinal\": 14, \"subMenuId\": null, \"value\": \"\", \"isDefault\": false, \"parentModuleId\": 13381}, {\"ActionName\": null, \"CategoryId\": null, \"Id\": 0, \"InputType\": \"NumericInput\", \"Label\": \"subNumeric\", \"TypeId\": null, \"apiId\": 13389, \"attachmentPropertyIds\": [], \"isEditable\": true, \"isVisible\": true, \"locationId\": null, \"ordinal\": 15, \"subMenuId\": null, \"value\": \"\", \"isDefault\": false, \"parentModuleId\": 13381}, {\"ActionName\": null, \"CategoryId\": null, \"Id\": 0, \"InputType\": \"SeparatedFeetAndInchesInput\", \"Label\": \"subSeparatedFeetAndInches\", \"TypeId\": null, \"apiId\": 13390, \"attachmentPropertyIds\": [], \"isEditable\": true, \"isVisible\": true, \"locationId\": null, \"ordinal\": 16, \"subMenuId\": null, \"value\": \"\", \"isDefault\": false, \"parentModuleId\": 13381}]}"
# Destringify the JSON string
destringified_data = json.loads(json_string1)

# Print the destringified data
print(destringified_data)
